### ISSUE TITLE
Farmer and cactus

### ISSUE THREAD

**Issue by makjak** [kepler155c/opus-apps#10]
I use develop 1.8 the last one that you have.
I use a lot the farmer app but i have not solve the problem with cactus.
When I plant one it harvest it immediately. i place two and farmer dont pick up (if it is down the second) but sometimes the second one it disappears because of the first cactus.
is it possible farmer to be worked with cactus like Sugar canes?
I change the command to bash but it smashed it and I loose it...
Also is it possible to make farmer for pam harvest craft?
when I place something in the config file it just ignore it... (with the right mature)

Thanks again for you great work

**Comment by kepler155c** [comment]
Make sure to plant cactus 1 block lower than the rest of the crops. The sand needs to be 2 blocks below the turtle (not 1 like the rest of the crops).

Using the block scanner, make sure you have the correct names for the pam harvest craft crops. I'll try this out myself as well.

**Comment by makjak** [comment]
Thank you farming cactus's is working perfectly...
As for pam harvest craft I used craft tweaker to find the name and placed it in the config of farmer. also I saw that the mature was in 3 steps and I placed mature 3.
I do not know how to see the block scanner output...

Also after the update I saw that the super treefarm is not working and I roll back the version to the older one.
The error was in the opus.utils  split.... do you want to place another issue?
As for the scanning miner its away the best miner ever... but when it goes to a chunk that is not loaded then it goes offline and sometimes when i was close its goes to home... other times I loose it.. and make a new one... is in plethora peripheral something to use it as chunk loader?

**Comment by makjak** [comment]
Great I used the block scanner and I found that the name was different than the one I had from crafttweeker and I made the turtle to harvest them and now i will try to make it plant again...

**Comment by kepler155c** [comment]
I tried harvesting one of pam's crops in the modpack I have. Here's what I found:
The turtle was able to harvest the crop, but not able to replant. In my version, the crop that was harvested returned a berry instead of a seed. But, here's what I did:

Using my neural interface with a blocks scanner, I stood on the crop and did peripheral.wrap('back').getBlockMeta(0, 0, 0)
Note that you might need to do getBlockMeta(0, -1, 0) -- possibly even -2 for y (depends on cc version)

To get the seed name, I placed the seed in the first slot on my hotbar and did:
peripheral.wrap('back').getInventory.list()[1]

Using this info, I added this entry to the config:
```
  [ "harvestcraft:pamcandleberrycrop" ] = {
    mature = 3,
    action = "plant",
    seed = "harvestcraft:pamcandleberryseeditem",
  },
```

But, as I said, no seeds were returned... If you are using crop sticks or something else, maybe that could be the issue.

I did a big rewrite of the superTreeFarm program - sorry should have given some type of warning. But, to fix, place the turtle back in the starting point, remove usr/config/superTreeFarm and give the turtle a scanner, sensor, chest and furnace. This update fixed a bunch of issues.

As for the system update, you will need to update all the packages as well as running the System->Update. If you still have issues, you can safely remove the sys directory (all your data is in usr) then reinstall using pastebin run uzghlbnc.

For the scanningMiner, you can give it a max range by doing something like:
scanningMiner -c 50

This will stop mining after 50 chunks (done in a spiral) and return back to starting point.

**Comment by makjak** [comment]
ScanningMiner its working like charm.
I fix superTreeFarm like you said and its working perfectly and bigger area as I saw...

As for the neutral interface when I run the command to see the first item in my hotbar (peripheral.wrap('back').getInventory().list()[1]) I receive an error 
lua:1: attempt to call field 'getInventory' (a nil value)

**Comment by makjak** [comment]
Milo has a problem with scan feature in machines.
It scans at the users inventory and not turtle.
Also the transfer feature is not working.. this is what I am doing.. I pick a previous storage chest and I choose Transfer and in the list I pick something else. after that I see at the monitor that it empty them from the inventory but none is transferred to the new location. So I rescan storage and I see the item with the correct value in my storage...

**Comment by kepler155c** [comment]
Transfer in milo has been fixed to update cache
