### ISSUE TITLE
Turtles not returning after swarm abort.

### ISSUE THREAD

**Issue by rangerdude** [kepler155c/opus-apps#19]
Mining with 2-6  turtles, when aborted almost all turtles just stop where they are at.
A few may continue for 30-45 digging. But then stop also.

I am playing on a server 1.12.2

Also a second issue that has started happening is swarm turtles are breaking other swarm turtles loosing all the goods.

**Comment by xAnavrins** [comment]
I've had this happen many times too
When mining, I go in a straight line, queue up some blocks, then I go back to get my drop chest, then back to the end of the mine, sometime it'll result in the turtles just going uncontrollably in the oposite direction.

**Comment by xAnavrins** [comment]
![2019-11-18_21 09 12](https://user-images.githubusercontent.com/5376823/69110316-59e00c80-0a48-11ea-8282-07128d29d2a1.png)

Sometime, the scanner will scan ores that are much farther away from the player, unsure if this caused by an ores.lua/canvas3d bug or the Block Scanner, the latter could explain why turtles tries to go to some place far away.

**Comment by xAnavrins** [comment]
I'm thinking https://github.com/kepler155c/opus/commit/942f0bda92f0aac48bf157ebef9a2c79791a294a might fix this, please report if that still happens.

**Comment by xAnavrins** [comment]
This has not happened to me since, so I will assume that it is fixed.
